libeconf.h: add missing sys/types.h header (#171)
required for mode_t, gid_t, uid_t

> it does not build otherwise (against musl libc):
> 
> ```
> 
> /home/demon/src/aports/main/libeconf/src/libeconf-0.4.7/include/libeconf.h:686:32: error: unknown type name 'uid_t'
>   686 | extern void econf_requireOwner(uid_t owner);
>       |                                ^~~~~
> /home/demon/src/aports/main/libeconf/src/libeconf-0.4.7/include/libeconf.h:694:32: error: unknown type name 'gid_t'
>   694 | extern void econf_requireGroup(gid_t group);
>       |                                ^~~~~
> /home/demon/src/aports/main/libeconf/src/libeconf-0.4.7/include/libeconf.h:703:38: error: unknown type name 'mode_t'
>   703 | extern void econf_requirePermissions(mode_t file_perms, mode_t dir_perms);
>       |                                      ^~~~~~
> /home/demon/src/aports/main/libeconf/src/libeconf-0.4.7/include/libeconf.h:703:57: error: unknown type name 'mode_t'
>   703 | extern void econf_requirePermissions(mode_t file_perms, mode_t dir_perms);
>       |                                                         ^~~~~~
> ```
> 
> there's a few alternate headers that would also have them, i guess: https://man7.org/linux/man-pages/man7/system_data_types.7.html



> it does not build otherwise (against musl libc):
> 
> ```
> 
> /home/demon/src/aports/main/libeconf/src/libeconf-0.4.7/include/libeconf.h:686:32: error: unknown type name 'uid_t'
>   686 | extern void econf_requireOwner(uid_t owner);
>       |                                ^~~~~
> /home/demon/src/aports/main/libeconf/src/libeconf-0.4.7/include/libeconf.h:694:32: error: unknown type name 'gid_t'
>   694 | extern void econf_requireGroup(gid_t group);
>       |                                ^~~~~
> /home/demon/src/aports/main/libeconf/src/libeconf-0.4.7/include/libeconf.h:703:38: error: unknown type name 'mode_t'
>   703 | extern void econf_requirePermissions(mode_t file_perms, mode_t dir_perms);
>       |                                      ^~~~~~
> /home/demon/src/aports/main/libeconf/src/libeconf-0.4.7/include/libeconf.h:703:57: error: unknown type name 'mode_t'
>   703 | extern void econf_requirePermissions(mode_t file_perms, mode_t dir_perms);
>       |                                                         ^~~~~~
> ```
> 
> there's a few alternate headers that would also have them, i guess: https://man7.org/linux/man-pages/man7/system_data_types.7.html

OK, thanks for clearance !